###
GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
  "title": "Another String11",
  "author": "Another String22",
  "url": "http://yahoo.com",
  "likes": "69"
}